---
title: "Maize Genetics Awards:"
---

### 2026 Maize Genetics Cooperation Community Awards

The MGC Community Awards will be revealed in the awards ceremony at the meeting, and this page will be updated following the conclusion of that ceremony.
Stay tuned!

### The Barbara McClintock Prize for Plant Genetics and Genome Studies

This award has been created to memorialize the unequalled contributions of Dr. McClintock through providing recognition to the most outstanding plant geneticists of the present era. In memory of the many contributions of Dr. McClintock, this Prize will be awarded each year to one or more of the most creative minds and productive scientists in the study of plant genome structure, function and evolution, including the analysis of gene regulation and epigenetics. 

The 2026 Barbara McClintock Prize for Plant Genetics and Genome Studies has been awarded to Dr. Joseph Ecker of the Salk Institute for Biological Studies who will present a McClintock Prize Address on Thursday, February 26, 8:40 pm (See Page 35). 

(See https://maizegdb.org/mgc/awards/ for details about each award) 

In addition, the maize genetics community participates in the ROOT & SHOOT RCN project (DBI- 2134321). The ROOT & SHOOT group of seven plant science organizations was awarded a five-year grant through the NSF’s LEAPS [LEAding cultural change through Professional Societies (LEAPS) of Biology] program. This Research Coordination Network (RCN) includes American Phytopathological Society (APS), American Society of Plant Biologists (ASPB), American Society of Plant Taxonomists (ASPT), Botanical Society of America (BSA), International Society for Molecular Plant Microbe Interactions (IS-MPMI), Maize Genetics Cooperation (MGC), North American Arabidopsis Steering Committee (NAASC), as well as other organizations that serve marginalized scientists.


### The 2026 Attendance/Travel Awards Program

The maize community offers several attendance and travel awards to encourage attendance at the Annual Maize Genetics Meeting (MGM). There are several programs that provide travel/attendance awards; e.g. Disciplinary Breadth (DB), Expanding Institutional Access (EIA), and a general program to support first time attendees. The Maize Genetics Meeting also partners with the ROOT & SHOOT (R&S) Research Coordination Network to allow two first-time attendees to attend the meeting. 

Here are the awardees for 2026; please congratulate these scientists and welcome them to our famously hospitable conference! 

**Undergraduate Student**

- Abigail McCarthy, Ohio State University Poster # 71

**Graduate Student**

- Jiyun Go, Chungnam National University Poster # 110
- Maria Schoen, IPK Gatersleben Poster # 116
- Tiago Corrêa, University of São Paulo Poster # 184
- Mythri Bikkasani, Punjab Agricultural University Poster # 250
- Ana Laura Marassi Maronezi, University of São Paulo Poster # 183
- Elliot Braun, Michigan State University Poster # 158
- Libia Gomez-Trejo, University of Nebraska - Lincoln Poster # 207

### Broadening International Participation Awards

The 2026 Broadening International Participation Award program seeks to promote international attendance for researchers from countries that are historically under-represented at the Maize Meeting. This 2026 award program seeks to enrich the maize community and broaden the opportunities to learn about maize genetics by connecting with scientists in the maize genetics community, exploring potential collaborations, and developing career contacts. BIP awardees receive waived registration to the recorded talks and sessions. 

**Graduate Student **

- Memis Bilgici