---
title: "General Information"
---

## Meeting Registration

- Thursday: 3:00 PM to 9:30 PM: Congress-Foyer
- Friday: 7:30 AM to 12:30 PM: Congress-Foyer

## Meals

All meals will be served buffet style in the Rottisserie + Glass Hall combined, except for the Saturday dinner which will be held at Frueh Brewery. Coffee, tea, and soft drinks are available at no charge during the beverage breaks.

## Talks and Posters

All Talks will be presented in Hall 1.

Posters will be presented in Hall 1 and Hall 2. Posters should be hung Thursday starting at 3 PM and stay up until Sunday morning, but must be removed by 9 AM on Sunday. During poster sessions, presenters of odd number posters are asked to stand by their posters 1:00-2:30 PM on Friday and 2:30-4:00 PM on Saturday. Presenters of even numbered posters should stand by their posters 2:30-4:00 PM on Friday and 1:00-2:30 PM on Saturday.

The maize meeting is a forum for presentation and discussion of unpublished material. **Photographing or recording of talks and posters is not allowed**.

## Health and Safety Policy

The Maize Genetics Cooperation (MGC) is committed to the health and safety of all Cooperation members and attendees of the Annual Maize Genetics Meeting (MGM). We do not require masks to be worn during the meeting. However, please be sensitive to the immunocompromised and those practicing physical distancing. 

<span style="color:firebrick">If you are feeling unwell, please stay in your hotel room and contact Tricia Simmons at tricia.simmons\@conferencedirect.com.</span> A local pharmacy is a 4-minute walk away at the following address: 

```
Augustiner-Apotheke 
Martinstraße 16-20 
50667 
Köln Germany 
```

<span style="color:firebrick">In case of emergency, call Germany’s emergency services at 112.</span> Most emergency operators speak English but it is not guaranteed.

## Hospitality

After the evening sessions on Thursday and Friday there will be informal socializing and poster gazing in the Halls 1 & 2, and the Congress-Foyer, with refreshments provided from 9 PM - 11 PM and a cash bar until 12 AM. On Saturday evening there will be a special dinner at Frueh Brewery, and the conference will walk there together at 7:30 PM after the Community Session.

## Access to recorded sessions

All talks and sessions will be recorded and made available to each meeting registrant. Registrants will receive an invitation email to view the recordings within 1-2 weeks after the meeting concludes from the Maize Genetics Cooperation (noreply-maize\@iastate.edu). If you do not receive the email by March 31st, please check your junk/spam folder. If you still haven’t received it, or you are having issues with the site where the videos are hosted, please email john.portwood\@usda.gov.

## Social Media Policy

By default, it is our policy to not share content from talks, posters, and abstracts on social media unless the author explicitly gave permission to do so when they submitted their abstract. Authors who gave such permission will have a symbol displayed next to their abstract in this book: [2026Program.pdf](https://documents.maizegdb.org/maizemeeting/abstracts/2026Program.pdf)

## Steering Committee

Please share your suggestions and comments about the meeting with the 2026 Steering Committee

|  |  |  |
|------------------------|------------------------|------------------------|
| Role | Person | Email |
| Chair | Frank Hochholdinger | hochhold\@uni-bonn.de |
| Co-Chair | Anthony Studer | astuder\@illinois.edu |
| Previous Chair | Sherry Flint-Garcia | sherry.flint-garcia\@usda.gov |
| Committee Member | Oyenike Adeyemo | aoadeyemo\@unilag.edu.ng |
| Committee Member | Hank Bass | bass\@bio.fsu.edu |
| Committee Member | Sarah Jensen | sarah.jensen\@syngenta.com |
| Committee Member | Sara Larsson | sara.larsson\@pioneer.com |
| Committee Member | Penelope Lindsay | penelope.lindsay\@oregonstate.edu |
| Committee Member | Yue Liu | yueliu\@iastate.edu |
| Committee Member | Katie Murphy | kmurphy\@danforthcenter.org |
| Committee Member | Cinta Romay | mcr72\@cornell.edu |
| Committee Member | Sylvia Morais de Sousa Tinoco | sylvia.sousa\@embrapa.br |
| Committee Member | Graziana Taramino | graziana.taramino\@bayer.com |
| Committee Member | Feng Tian | ft55\@cau.edu.cn |
| Ex-officio - MaizeGDB | Carson Andorf |  |
| Ex-officio - Treasurer | Erin Sparks |  |
| Ex-officio - Planning / Audio Visual | Darwin Campbell |  |
| Ex-officio - Guru | Marty Sachs |  |
| Ex-officio - Logistics Coordinator | John Portwood |  |
| Meeting planning - Conference Direct | Tricia Simmons |  |
| Meeting planning - Conference Direct | Michelle Kirn |  |

## Acknowledgements

Many thanks go to Carson Andorf, Daniel Kick, John Portwood, the MaizeGDB staff from the USDA-ARS, and Darwin Campbell (Iowa State University) for their tremendous efforts in organizing, assembling, and advertising the conference program. We also greatly thank Tricia Simmons, Michelle Kirn, and their team at ConferenceDirect for helping to organize and implement the conference registration platform, handling meeting logistics with the venue staff, and dealing with many other issues. Special thanks are also extended to the Maritim Hotel staff for their help in organizing this conference. Thanks go to Sarah Jensen, Graziana Taramino, and Sara Larsson for their efforts in securing funding to offset meeting costs. Finally, many, many thanks go to the Steering Committee for organizing the 68th Maize Genetics Meeting
